### ISSUE TITLE
Gopkg.lock is not in sync with vendor

### ISSUE THREAD

**Issue by joneskoo** [Xe/twirp-codegens#2]
I wanted to check what modifications have been made in the packages in vendor/. Gopkg.lock references non-public sources or something and dep ensure is not happy.

Are the modifications in the vendored dependencies required?

```
[joneskoo@grant twirp-codegens]$ dep ensure
Solving failure: No versions of github.com/twitchtv/twirp met constraints:
	Xe/feat/make-gen-public: unable to update checked out version: fatal: reference is not a tree: e3dd5a1b97420399abc3b5e2d80aab102aa9330e
: command failed: [git checkout e3dd5a1b97420399abc3b5e2d80aab102aa9330e]: exit status 128
	v5.0.0: Could not introduce github.com/twitchtv/twirp (from https://github.com/Xe/twirp)@v5.0.0, as it is not allowed by constraint Xe/feat/make-gen-public from project github.com/Xe/twirp-codegens.
...
```

**Comment by Xe** [comment]
Yes, this code is based on a fork of internals of twirp. I need to fix these generators to use https://github.com/twitchtv/protogen instead of the hacked up copy of twirp I used to get this prototype out of the door.
